/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coline_airport_eddp2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.JTextPane;

/**
 *
 * @author dylan
 */
public class Cargas extends javax.swing.JPanel {

    JFileChooser chusito = new JFileChooser("C:\\Users\\dylan\\Desktop");
    File documento;

    /**
     * Creates new form Cargas
     */
    public Cargas() {
        initComponents();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        JBDest = new javax.swing.JButton();
        JBRut = new javax.swing.JButton();
        JBReserv = new javax.swing.JButton();
        JBCargar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 485));
        setMinimumSize(new java.awt.Dimension(590, 420));
        setPreferredSize(new java.awt.Dimension(600, 485));
        setLayout(null);

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 573, 284);

        JBDest.setText("Destinos");
        JBDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDestActionPerformed(evt);
            }
        });
        add(JBDest);
        JBDest.setBounds(20, 340, 135, 72);

        JBRut.setText("Rutas");
        JBRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRutActionPerformed(evt);
            }
        });
        add(JBRut);
        JBRut.setBounds(160, 340, 125, 70);

        JBReserv.setText("Reservas");
        JBReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBReservActionPerformed(evt);
            }
        });
        add(JBReserv);
        JBReserv.setBounds(290, 340, 136, 72);

        JBCargar.setText("Cargar");
        JBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCargarActionPerformed(evt);
            }
        });
        add(JBCargar);
        JBCargar.setBounds(10, 10, 90, 28);

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(110, 10, 79, 28);

        getAccessibleContext().setAccessibleName("Cargas");
    }// </editor-fold>//GEN-END:initComponents

    private void JBDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDestActionPerformed
        jTextPane1.setText(cargarDestinos(jTextPane1.getText()));
    }//GEN-LAST:event_JBDestActionPerformed

    private void JBRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRutActionPerformed
        jTextPane1.setText(cargarRutas(jTextPane1.getText()));
    }//GEN-LAST:event_JBRutActionPerformed

    private void JBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCargarActionPerformed
        Abrir();
    }//GEN-LAST:event_JBCargarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextPane1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void JBReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBReservActionPerformed
         jTextPane1.setText(cargarRersev(jTextPane1.getText()));
    }//GEN-LAST:event_JBReservActionPerformed

    public void Abrir() {
        int entero = chusito.showOpenDialog(null);
        documento = chusito.getSelectedFile();
        JTextArea TxtF = new JTextArea();
        if (entero == chusito.APPROVE_OPTION) {
            try {
                BufferedReader lector = new BufferedReader(new FileReader(documento));
                String Temporal;
                while ((Temporal = lector.readLine()) != null) {
                    TxtF.append(Temporal + "\n");
                }
                lector.close();
            } catch (FileNotFoundException ex) {
                System.out.println("Algo salio mal " + ex);
            } catch (IOException ex1) {
                System.out.println("Algo salio mal " + ex1);
            }
        }
        try {
            jTextPane1.setText(TxtF.getText());
        } catch (Exception e) {
            System.out.println("Error en el copiado al TextPane " + e);
        }
    }

    private static String cargarDestinos(java.lang.String texto) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.cargarDestinos(texto);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCargar;
    private javax.swing.JButton JBDest;
    private javax.swing.JButton JBReserv;
    private javax.swing.JButton JBRut;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private static String cargarRutas(java.lang.String texto) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.cargarRutas(texto);
    }

    private static String cargarRersev(java.lang.String texto) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.cargarRersev(texto);
    }

}
