/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coline_airport_eddp2;

import java.awt.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author dylan
 */
public class Graficas extends javax.swing.JPanel {

    /**
     * Creates new form Graficas
     */
    public Graficas() {
        initComponents();
        this.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        JBDestinos = new javax.swing.JButton();
        JBRutas = new javax.swing.JButton();
        JBReser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new javax.swing.JLabel();
        Grafo = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("ImagenPanel");

        setMaximumSize(new java.awt.Dimension(600, 485));
        setMinimumSize(new java.awt.Dimension(600, 485));
        setPreferredSize(new java.awt.Dimension(600, 485));

        JBDestinos.setText("Destinos");
        JBDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDestinosActionPerformed(evt);
            }
        });

        JBRutas.setText("Rutas");
        JBRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRutasActionPerformed(evt);
            }
        });

        JBReser.setText("Hash Reservaciones");
        JBReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBReserActionPerformed(evt);
            }
        });

        lienzo.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(lienzo);

        Grafo.setText("Grafo_Mapa ");
        Grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Grafo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBReser)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBRutas)
                    .addComponent(JBReser)
                    .addComponent(JBDestinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Grafo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRutasActionPerformed

        ImageIcon destinos = new ImageIcon("C:\\Users\\dylan\\Documents\\NetBeansProjects\\Coline_Ariporto\\web\\Mat.png");
        destinos.getImage().flush();
        lienzo.setIcon(destinos);
        this.updateUI();
    }//GEN-LAST:event_JBRutasActionPerformed

    private void JBDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDestinosActionPerformed
        ImageIcon destinos = new ImageIcon("C:\\Users\\dylan\\Documents\\NetBeansProjects\\Coline_Ariporto\\web\\Arbol_B.png");
        destinos.getImage().flush();
        lienzo.setIcon(destinos);
        this.updateUI();
    }//GEN-LAST:event_JBDestinosActionPerformed

    private void JBReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBReserActionPerformed
        ImageIcon destinos = new ImageIcon("C:\\Users\\dylan\\Documents\\NetBeansProjects\\Coline_Ariporto\\web\\Hash.png");
        destinos.getImage().flush();
        lienzo.setIcon(destinos);
        this.updateUI();
    }//GEN-LAST:event_JBReserActionPerformed

    private void GrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrafoActionPerformed
        ImageIcon destinos = new ImageIcon("C:\\Users\\dylan\\Documents\\NetBeansProjects\\Coline_Ariporto\\web\\Rutas.png");
        destinos.getImage().flush();
        lienzo.setIcon(destinos);
        this.updateUI();
    }//GEN-LAST:event_GrafoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Grafo;
    private javax.swing.JButton JBDestinos;
    private javax.swing.JButton JBReser;
    private javax.swing.JButton JBRutas;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lienzo;
    // End of variables declaration//GEN-END:variables

    private static String getImagHash() {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.getImagHash();
    }
}
