/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coline_airport_eddp2;

/**
 *
 * @author dylan
 */
public class Modificacion extends javax.swing.JPanel {

    /**
     * Creates new form Modificacion
     */
    public Modificacion() {
        initComponents();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeleteRuta = new javax.swing.JButton();
        ModRuta = new javax.swing.JButton();
        cost = new javax.swing.JTextField();
        tiempo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        orig = new javax.swing.JTextField();
        NewRuta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        piloto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        llave = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        DeleteReserv = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        orig_Re = new javax.swing.JTextField();
        dest_Re = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        NEwReserv = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        NAme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rutaspane = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        opcion = new javax.swing.JTextField();
        Ruta = new javax.swing.JButton();
        Reserv = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 485));
        setMinimumSize(new java.awt.Dimension(600, 485));
        setPreferredSize(new java.awt.Dimension(600, 485));

        jLabel1.setText("Costo");

        jLabel2.setText("Tiempo");

        DeleteRuta.setText("Delete Ruta");
        DeleteRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRutaActionPerformed(evt);
            }
        });

        ModRuta.setText("Modificar");
        ModRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModRutaActionPerformed(evt);
            }
        });

        jLabel4.setText("Destino");

        jLabel5.setText("Origen");

        NewRuta.setText("Crear");
        NewRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRutaActionPerformed(evt);
            }
        });

        jLabel6.setText("Piloto");

        jLabel7.setText("llave de cifrado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(DeleteRuta)
                        .addGap(39, 39, 39)
                        .addComponent(ModRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(orig))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dest)
                                    .addComponent(cost)
                                    .addComponent(tiempo)
                                    .addComponent(piloto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(llave)))
                        .addGap(38, 38, 38))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewRuta)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(orig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(piloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(llave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewRuta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRuta)
                    .addComponent(ModRuta))
                .addGap(31, 31, 31))
        );

        jLabel3.setText("Codigo");

        DeleteReserv.setText("Delete Rerserv");
        DeleteReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteReservActionPerformed(evt);
            }
        });

        jLabel8.setText("Origen");

        jLabel9.setText("Destino");

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NEwReserv.setText("Reservar");
        NEwReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEwReservActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre");

        jScrollPane1.setViewportView(Rutaspane);

        jLabel11.setText("Selecciona tu opcion");

        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(DeleteReserv))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel10)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(NAme, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NEwReserv))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dest_Re, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(orig_Re, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(orig_Re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dest_Re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(NAme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NEwReserv, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(DeleteReserv)
                .addGap(36, 36, 36))
        );

        Ruta.setText("Ruta");

        Reserv.setText("Reservacion");
        Reserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reserv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reserv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Ruta.getAccessibleContext().setAccessibleName("MRuta");
        Reserv.getAccessibleContext().setAccessibleName("MReserv");

        getAccessibleContext().setAccessibleName("Modificacion");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void ModRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModRutaActionPerformed
        if (!(orig.getText().equalsIgnoreCase("") || dest.getText().equalsIgnoreCase("") || cost.getText().equalsIgnoreCase("") || tiempo.getText().equalsIgnoreCase(""))) {
            if (modRuta(orig.getText(), dest.getText(), cost.getText(), tiempo.getText())) {
                System.out.println("Ruta modificada");
            }
        }
    }//GEN-LAST:event_ModRutaActionPerformed

    private void DeleteRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRutaActionPerformed
        if (!(orig.getText().equalsIgnoreCase("") || dest.getText().equalsIgnoreCase(""))) {
            if (eliminarRuta(orig.getText(), dest.getText())) {
                System.out.println("Ruta eliminada");
            };
        }
    }//GEN-LAST:event_DeleteRutaActionPerformed

    private void NewRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRutaActionPerformed
        if (!(orig.getText().equalsIgnoreCase("") || dest.getText().equalsIgnoreCase("") || cost.getText().equalsIgnoreCase("") || tiempo.getText().equalsIgnoreCase(""))) {
            if (newRuta(orig.getText(), dest.getText(), cost.getText(), tiempo.getText(), piloto.getText(), llave.getText())) {
                System.out.println("Ruta creada");
            }
        }
    }//GEN-LAST:event_NewRutaActionPerformed

    private void ReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String opc = "";
            String rutas[] = getListadoRutas(orig_Re.getText(), dest_Re.getText()).split("\n");
            for (int i = 0; i < rutas.length; i++) {
                opc += rutas[i];

            }
            Rutaspane.setText(opc);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NEwReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEwReservActionPerformed
        try {
            int cod = Integer.parseInt(opcion.getText());
            if (cod > 0) {
                newReserv(cod + "", NAme.getText());
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_NEwReservActionPerformed

    private void DeleteReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteReservActionPerformed
        eliminarReserva(cod.getText());
    }//GEN-LAST:event_DeleteReservActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteReserv;
    private javax.swing.JButton DeleteRuta;
    private javax.swing.JButton ModRuta;
    private javax.swing.JTextField NAme;
    private javax.swing.JButton NEwReserv;
    private javax.swing.JButton NewRuta;
    private javax.swing.JButton Reserv;
    private javax.swing.JButton Ruta;
    private javax.swing.JTextPane Rutaspane;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField dest;
    private javax.swing.JTextField dest_Re;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField llave;
    private javax.swing.JTextField opcion;
    private javax.swing.JTextField orig;
    private javax.swing.JTextField orig_Re;
    private javax.swing.JTextField piloto;
    private javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables

    private static boolean modRuta(java.lang.String orig, java.lang.String dest, java.lang.String costo, java.lang.String tiempo) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.modRuta(orig, dest, costo, tiempo);
    }

    private static boolean eliminarRuta(java.lang.String orig, java.lang.String dest) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.eliminarRuta(orig, dest);
    }

    private static boolean newRuta(java.lang.String orig, java.lang.String dest, java.lang.String costo, java.lang.String tiempo, java.lang.String piloto, java.lang.String llave) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.newRuta(orig, dest, costo, tiempo, piloto, llave);
    }

    private static boolean eliminarReserva(java.lang.String id) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.eliminarReserva(id);
    }

    private static String getListadoRutas(java.lang.String orig, java.lang.String dest) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.getListadoRutas(orig, dest);
    }

    private static boolean newReserv(java.lang.String cod, java.lang.String name) {
        web_services.CargarDatos_Service service = new web_services.CargarDatos_Service();
        web_services.CargarDatos port = service.getCargarDatosPort();
        return port.newReserv(cod, name);
    }
}
